name: Lint

on:
  push:
    branches: ["*"]

jobs:
  styles:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Lint Check
        run: npm run lint
